# Generated by Django 5.0.6 on 2025-01-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypartner',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='delivery_id_proofs/'),
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_licenses/'),
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
    ]
