# Generated by Django 5.0.6 on 2025-01-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_deliverypartner_id_proof_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverypartner',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='deliverypartner',
            name='total_deliveries',
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='insurance_document',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_partners/insurance/'),
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='phone_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_partners/profile_pics/'),
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='vehicle_registration',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_partners/vehicle_registrations/'),
        ),
        migrations.AlterField(
            model_name='deliverypartner',
            name='id_proof',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_partners/id_proofs/'),
        ),
        migrations.AlterField(
            model_name='deliverypartner',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_partners/licenses/'),
        ),
        migrations.AlterField(
            model_name='deliverypartner',
            name='license_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='deliverypartner',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliverypartner',
            name='vehicle_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='deliverypartner',
            name='vehicle_type',
            field=models.CharField(max_length=50),
        ),
    ]
