# Generated by Django 5.0.6 on 2024-08-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artisan',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artisan',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='artisan',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='artisan',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='artisan',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='artisan',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='artisan',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
