# Generated by Django 5.0.6 on 2024-08-24 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='gst_certificate',
            field=models.FileField(blank=True, null=True, upload_to='gst_certificates/'),
        ),
        migrations.AddField(
            model_name='artisan',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='AuthenticityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='authenticity_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authenticity_documents', to='accounts.product')),
            ],
        ),
    ]
