# Generated by Django 5.0.6 on 2025-02-18 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_delivery_coordinates'),
        ('accounts', '0005_notification'),
    ]

    operations = [
    ]
