# Generated by Django 5.0.6 on 2025-02-19 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20250218_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryrating',
            name='delivery_partner',
        ),
        migrations.RemoveField(
            model_name='deliverystatushistory',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='deliverystatushistory',
            name='location_lng',
        ),
        migrations.AlterField(
            model_name='deliveryrating',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.delivery'),
        ),
        migrations.AlterField(
            model_name='deliveryrating',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.CreateModel(
            name='DeliveryEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('artisan_share', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='earning', to='accounts.delivery')),
                ('delivery_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='accounts.deliverypartner')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['delivery_partner', 'status'], name='accounts_de_deliver_916846_idx'), models.Index(fields=['created_at'], name='accounts_de_created_8d7462_idx')],
            },
        ),
    ]
