# Generated by Django 5.0.6 on 2025-02-20 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_deliverypartner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverystatushistory',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='deliverystatushistory',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliverystatushistory',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='accounts.delivery'),
        ),
        migrations.AlterField(
            model_name='deliverystatushistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted by Partner'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('near_delivery', 'Near Delivery Location'), ('delivered', 'Delivered'), ('failed', 'Delivery Failed'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
