# Generated by Django 5.0.6 on 2025-02-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_deliverystatushistory_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='destination_lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='destination_lng',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
