# Generated by Django 5.0.6 on 2025-02-20 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_delivery_destination_lat_delivery_destination_lng'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverystatushistory',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Delivery Status Histories'},
        ),
        migrations.RemoveField(
            model_name='deliverystatushistory',
            name='location',
        ),
        migrations.RemoveField(
            model_name='deliverystatushistory',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='deliverystatushistory',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='deliverystatushistory',
            name='location_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='deliverystatushistory',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='accounts.delivery'),
        ),
        migrations.AlterField(
            model_name='deliverystatushistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned to Delivery Partner'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
