# Generated by Django 5.0.6 on 2024-09-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_chatmessage_options_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticitydocument',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
