# Generated by Django 5.0.6 on 2025-04-02 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_order_delivered_at_remove_order_shipped_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypartner',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryrating',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='accounts.delivery'),
        ),
    ]
